Pipeline integration
SODALITE-EU/iac-platform-stack pull request #32
Opened 2021-03-04 12:03 UTC by alexmaslenn

Updated component versions and integrated security for deployment pipeline

2021-03-04 21:27 UTC, mihaTrajbaric requested changes
I think it is a really good thing to update the components' versions. I think we still have some outdated versions (xopera-rest-api, toscaverifier, workflowverifier,...) and some components are simply set to latest (keycloak, vault, pds,...)

It would be a good thing to control all the versions so we can ensure future deployability of this version of iac-platform-stack

2021-03-04 21:27 UTC, mihaTrajbaric commented on openstack/input.yaml
> -  XOPERA_DATABASE_PASSWORD: password
This should not be removed.

2021-03-05 10:45 UTC, alexmaslenn commented on openstack/input.yaml
> -  XOPERA_DATABASE_PASSWORD: password
Sure thing. IDK how this happened.

2021-03-05 10:51 UTC, alexmaslenn commented
@mihaTrajbaric I agree. Lets make a new issue and update all components versions. Some outdated components however were probably not really updated since.

2021-03-05 12:56 UTC, mihaTrajbaric commented
> @mihaTrajbaric I agree. Lets make a new issue and update all components versions. Some outdated components however were probably not really updated since.

Ok, I agree

2021-03-05 12:56 UTC, mihaTrajbaric approved these changes
:+1:

2021-03-05 12:57 UTC, merged